version: '3'
services:
  app:
    build: ./docker/app
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./app:/var/www/html
      - node_modules_volume:/var/www/html/node_modules
    stdin_open: true
    tty: true
volumes:
  node_modules_volume: